# yujin lee, 12193075 - Operating Systems Project 2
synch_pthread: synch_pthread.c
	gcc -g synch_pthread.c -o synch_pthread -lpthread

synch_semaphore: synch_semaphore.c
	gcc -g synch_semaphore.c -o synch_semaphore -lpthread
